var N = null;var sourcesIndex = {};
sourcesIndex["dvm"] = {"name":"","files":["dvm.rs"]};
sourcesIndex["dvm_cli"] = {"name":"","files":["config.rs","info_service.rs","lib.rs","logging.rs"]};
sourcesIndex["dvm_compiler"] = {"name":"","dirs":[{"name":"cmd","files":["build.rs","check.rs","init.rs","mod.rs","new.rs","update.rs"]},{"name":"embedded","files":["ds_loader.rs","mod.rs"]},{"name":"mv","dirs":[{"name":"dependence","files":["extractor.rs","loader.rs","mod.rs"]}],"files":["bech32.rs","builder.rs","disassembler.rs","mod.rs","preprocessor.rs"]}],"files":["lib.rs","manifest.rs"]};
sourcesIndex["dvm_data_source"] = {"name":"","files":["grpc.rs","lib.rs","metrics.rs","mock.rs","module_cache.rs"]};
sourcesIndex["dvm_info"] = {"name":"","dirs":[{"name":"metrics","files":["collector.rs","live_time.rs","meter.rs","metric.rs","mod.rs","prometheus.rs"]}],"files":["config.rs","heartbeat.rs","lib.rs","task.rs","web.rs"]};
sourcesIndex["dvm_lang"] = {"name":"","dirs":[{"name":"bytecode","dirs":[{"name":"verification","files":["bytecode.rs","mod.rs","whitelist.rs"]}],"files":["mod.rs"]}],"files":["lib.rs","stdlib.rs"]};
sourcesIndex["dvm_libra_deps"] = {"name":"","files":["lib.rs"]};
sourcesIndex["dvm_net"] = {"name":"","files":["endpoint.rs","lib.rs","serve.rs","unix.rs"]};
sourcesIndex["dvm_runtime"] = {"name":"","files":["gas_schedule.rs","lib.rs","move_vm.rs"]};
sourcesIndex["dvm_services"] = {"name":"","files":["compiler.rs","lib.rs","metadata.rs","vm.rs"]};
sourcesIndex["dvm_test_kit"] = {"name":"","files":["genesis.rs","grpc_client.rs","grpc_server.rs","lib.rs"]};
sourcesIndex["movec"] = {"name":"","files":["movec.rs"]};
sourcesIndex["status_table"] = {"name":"","files":["status-table.rs"]};
sourcesIndex["stdlib_builder"] = {"name":"","files":["stdlib-builder.rs"]};
createSourceSidebar();
